//! Message definitions emitted by the application and its widgets.

use super::*;

#[derive(Debug, Clone)]
pub enum Message {
    AppletPressed,
    TogglePanel,
    PanelClosed(Id),
    EscapePressed(Id),
    UpdateConfig(Config),
    NewChat,
    ToggleChatList,
    SelectChat(u64),
    ChatHovered(u64),
    ChatUnhovered(u64),
    MessageHovered(u64),
    MessageUnhovered(u64),
    BeginRenameChat(u64),
    RenameInputChanged(String),
    CommitRenameChat(String),
    CancelRenameChat,
    DeleteChat(u64),
    OpenSettings,
    CloseSettings,
    ChatScrolled(cosmic::iced::widget::scrollable::Viewport),
    ComposerEdited(widget::text_editor::Action),
    InlineEditEdited(widget::text_editor::Action),
    MessageViewerEdited(u64, widget::text_editor::Action),
    MarkdownLink(widget::markdown::Uri),
    SubmitComposer,
    SaveEditedMessage,
    CancelEditedMessage,
    StopGeneration,
    LoadingTick,
    ProviderEvent(provider::ProviderEvent),
    CopyMessage(u64),
    CopyCodeBlock {
        message_id: u64,
        block_index: usize,
        content: String,
    },
    ResetCopiedTarget(CopiedTarget),
    RetryRequest(u64),
    RegenerateLastAssistant(u64),
    EditUserMessage(u64),
    DeleteLastAssistant(u64),
    BranchConversation(u64),
    ProviderSelected(usize),
    OpenRouterKeyChanged(String),
    LmStudioUrlChanged(String),
    ContextLimitChanged(String),
    DefaultModelSelected(usize),
    ActiveModelSelected(usize),
    OpenAddModelModal,
    CloseSettingsModal,
    AddModelProviderSelected(usize),
    AddModelNameChanged(String),
    SaveAddedModel,
    RemoveSavedModel(usize),
    OpenSystemPromptModal,
    SystemPromptEdited(widget::text_editor::Action),
    SaveSystemPrompt,
    TestConnection,
    ConnectionTestFinished(Result<(), String>),
    SaveSettings,
}
