//! Message definitions emitted by the application and its widgets.

use super::*;
use crate::runtime::personalization::AiMigrationOutcome;

#[derive(Debug, Clone)]
pub enum Message {
    AppletPressed,
    TogglePanel,
    PanelClosed(Id),
    EscapePressed(Id),
    UpdateConfig(Config),
    NewChat,
    ToggleChatList,
    SelectChat(u64),
    ChatHovered(u64),
    ChatUnhovered(u64),
    HoverMessageRow(u64),
    LeaveMessageRow(u64),
    BeginRenameChat(u64),
    RenameInputChanged(String),
    CommitRenameChat(String),
    CancelRenameChat,
    DeleteChat(u64),
    OpenSettings,
    CloseSettings,
    ChatScrolled(cosmic::iced::widget::scrollable::Viewport),
    ComposerEdited(widget::text_editor::Action),
    InlineEditEdited(widget::text_editor::Action),
    ViewerEdited(u64, widget::text_editor::Action),
    MarkdownLink(widget::markdown::Uri),
    SubmitComposer,
    SaveInlineEdit,
    CancelInlineEdit,
    StopGeneration,
    LoadingTick,
    ProviderEvent(provider::ProviderEvent),
    CopyEntry(u64),
    CopyCodeBlock {
        message_id: u64,
        block_index: usize,
        content: String,
    },
    ResetCopiedTarget(CopiedTarget),
    RetryRequest(u64),
    RegenerateLastAssistant(u64),
    BeginUserEdit(u64),
    DeleteLastAssistant(u64),
    BranchConversation(u64),
    SettingsTabSelected(SettingsTab),
    ProviderSelected(usize),
    OpenRouterKeyChanged(String),
    LmStudioUrlChanged(String),
    ModelFilterSelected(usize),
    ProviderTimeoutChanged(String),
    ProviderRetryAttemptsChanged(String),
    ProviderRetryDelayChanged(String),
    ContextLimitChanged(String),
    DefaultModelSelected(usize),
    ActiveModelSelected(usize),
    OpenManageModelsModal,
    OpenManageMemoryModal,
    OpenAddModelModal,
    CloseSettingsModal,
    AddModelProviderSelected(usize),
    AddModelNameChanged(String),
    SaveAddedModel,
    RemoveSavedModel(usize),
    OpenSystemPromptModal,
    OpenResponseStyleModal,
    OpenMoreAboutYouModal,
    ImportPersonalizationFromFile,
    ImportPersonalizationFinished(
        Result<Option<(String, crate::personalization::PersonalizationSettings)>, String>,
    ),
    ExportPersonalizationToFile,
    ExportPersonalizationFinished(Result<Option<String>, String>),
    OpenAiMigrationModal,
    CopyAiMigrationPrompt,
    AiMigrationModelSelected(usize),
    AiMigrationEdited(widget::text_editor::Action),
    StartAiMigration,
    RetryAiMigration,
    ReturnToAiMigrationEditor,
    AiMigrationTick,
    AiMigrationFinished {
        request_id: u64,
        result: Result<AiMigrationOutcome, String>,
    },
    OpenPromptPreviewModal,
    SettingsModalEdited(widget::text_editor::Action),
    SaveSettingsModal,
    ProfileNameChanged(String),
    ProfileLanguageChanged(String),
    ProfileOccupationEdited(widget::text_editor::Action),
    HeaderListsSelected(usize),
    EmojiSelected(usize),
    PromptPreviewModeSelected(PromptPreviewMode),
    AddMemoryItem,
    MemorySearchChanged(String),
    MemoryItemChanged(usize, String),
    RemoveMemoryItem(usize),
    OpenResetPersonalizationConfirm,
    ConfirmResetPersonalization,
    SkillDatetimeToggled(bool),
    SkillClipboardToggled(bool),
    SkillFilesystemToggled(bool),
    TestConnection,
    ConnectionTestFinished(Result<(), String>),
    SaveSettings,
}
